Model:
  clip_model: "ViT-B/32"

Dataset:
  train_data_path: "data/nuscenes_tp_train.pt"
  eval_data_path: "data/nuscenes_tp_val.pt"
  min_points: 5

Train:
  device: "cuda"

  batch_size: 168
  epochs: 20
  learning_rate: 0.0005
  weight_decay: 0.2
  warmup_ratio: 0.01
  accumulation_steps: 2

  optimizer: "AdamW"

  scheduler:
    type: "cosine"
    num_cycles: 0.5

  # For resuming training
  checkpoint_path: "checkpoints/checkpoint_epoch5.pt"
  tensorboard_logdir: "runs/Sep11_01-24-10_etid-l17hrhk6cw.engr.tamu.edu"